version: '2'

services: 
    wordpress: 
        image: wordpress:php7.1
        ports:
            - 8080:80
        environment:
            WORDPRESS_DB_PASSWORD: 12345
        volumes:
            - ./:/var/www/html/wp-content/themes/lehmamic-wordpress-theme
    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 12345